@mums_initial = {
  "a" => "Ostler's",
  "b" => "Cobbler's",
  "c" => "Chandler's",
  "d" => "Clerk's",
  "e" => "Groom's",
  "f" => "Tinker's",
  "g" => "Sheperd's",
  "h" => "Peeler's",
  "i" => "Farmer's",
  "j" => "Fisher's",
  "k" => "Waggoner's",
  "l" => "Mason's",
  "m" => "Weaver's",
  "n" => "Squire's",
  "o" => "Hooper's",
  "p" => "Fletcher's",
  "q" => "Carpenter's",
  "r" => "Cooper's",
  "s" => "Slater's",
  "t" => "Founder's",
  "u" => "Bodger's",
  "v" => "Clogger's",
  "w" => "Slater's",
  "x" => "Diggers",
  "y" => "Drover's",
  "z" => "Ghillie's"
}

@first_initial = {
  "a" => "Golden",
  "b" => "Ruby",
  "c" => "Dark",
  "d" => "Mutty",
  "e" => "Sweet",
  "f" => "Best",
  "g" => "Old",
  "h" => "Strong",
  "i" => "Hoppy",
  "j" => "Pale",
  "k" => "Heavy",
  "l" => "Amber",
  "m" => "Vintage",
  "n" => "Special",
  "o" => "Warm",
  "p" => "Zesty",
  "q" => "Rustic",
  "r" => "Fruity",
  "s" => "Smooth",
  "t" => "Bitter",
  "u" => "Smokey",
  "v" => "Velvet",
  "w" => "Oatmeal",
  "x" => "Tangy",
  "y" => "Malty",
  "z" => "Blonde"
}

@birth_month = [
  "Badger",
  "Cow",
  "Toad",
  "Rabbit",
  "Pheasent",
  "Cock",
  "Ferret",
  "Donkey",
  "Goat",
  "Lobster",
  "Rat",
  "Spaniel"
]

@last_initial = {
  "a" => "Plucker",
  "b" => "Worrier",
  "c" => "Botherer",
  "d" => "Beater",
  "e" => "Fighter",
  "f" => "Wobbler",
  "g" => "Teaser",
  "h" => "Dodger",
  "i" => "Muncher",
  "j" => "Snapper",
  "k" => "Licker",
  "l" => "Slurper",
  "m" => "Fancier",
  "n" => "Choker",
  "o" => "Chaser",
  "p" => "Bitter",
  "q" => "Sniffer",
  "r" => "Tickler",
  "s" => "Lifter",
  "t" => "Shagger",
  "u" => "Fiddler",
  "v" => "Hunter",
  "w" => "Tosser",
  "x" => "Fixer",
  "y" => "Kisser",
  "z" => "Puller"
}
